name: tarantool_storage_sample
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  tarantool_storage:
    git: 
      url: https://github.com/antonbashir/dart-tarantool-storage/
      path: binding/dart
